name: Generate Report

on:
  push:
    branches:
      - main 
    paths:
      - report/**

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: 
            Go-Dependency-Cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            Go-Dependency-Cache-${{ runner.os }}-
      
      - name: Install Go Modules
        run: |
          go mod init ReportForge
          go get gopkg.in/yaml.v3
          go get github.com/russross/blackfriday/
          go get github.com/microcosm-cc/bluemonday
          go get github.com/xuri/excelize/v2
          go get github.com/chromedp/cdproto/page
          go get github.com/chromedp/chromedp
          go mod tidy 

      - name: Run Go Project
        run: go run engine/main.go 

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: Report.*
